criaCartao('Elden Ring', 'Qual é o nome do mundo em que se passa *Elden Ring*?', 'The Lands Between.')
criaCartao('Elden Ring', 'Quem é o criador de *Elden Ring*?', 'Hidetaka Miyazaki, com colaboração de George R. R. Martin.')
criaCartao('Elden Ring', 'Qual é o principal objetivo do jogador em *Elden Ring*?', 'Derrotar poderosos chefes e restaurar o Elden Ring.')
criaCartao('Fortnite', 'Qual é o nome do modo de jogo mais popular de *Fortnite*?', 'Battle Royale.')
criaCartao('Fortnite', 'Em *Fortnite*, o que é necessário para construir estruturas?', 'Você precisa de madeira, tijolo e metal.')
criaCartao('Fortnite', 'Qual foi o evento que causou a transformação do mapa em *Fortnite*?', 'O Evento do Buraco Negro.')
criaCartao('League of Legends', 'Qual é o nome do campo de batalha principal em *League of Legends*?', 'Summoner’s Rift.')
criaCartao('League of Legends', 'Em *League of Legends*, quantos jogadores formam uma equipe em uma partida padrão?', '5 jogadores.')
criaCartao('League of Legends', 'Qual é o nome do personagem mais popular de *League of Legends*, frequentemente chamado de "The Heart of the Freljord"?', 'Ashe.')
criaCartao('Minecraft', 'Qual é o objetivo principal de *Minecraft* no modo sobrevivência?', 'Sobreviver e explorar o mundo gerado aleatoriamente.')
criaCartao('Minecraft', 'Em *Minecraft*, qual é a principal maneira de obter diamantes?', 'Cavando até o nível 11 e minerando blocos de diamante.')
criaCartao('Minecraft', 'Qual é o nome do inimigo final de *Minecraft*?', 'The Ender Dragon.')
criaCartao('Call of Duty', 'Em *Call of Duty: Warzone*, qual é o modo de jogo mais popular?', 'Battle Royale.')
criaCartao('Call of Duty', 'Em *Call of Duty*, qual é a principal mecânica de jogo em que os jogadores lutam em um ambiente de guerra moderna?', 'Tiros em primeira pessoa e combate em equipe.')
criaCartao('Apex Legends', 'Qual é a principal característica de cada personagem em *Apex Legends*?', 'Cada personagem tem uma habilidade única, chamada de "Legend Ability".')
criaCartao('Apex Legends', 'Em *Apex Legends*, qual é o nome da zona que vai encolhendo durante a partida?', 'O Círculo.')
criaCartao('Overwatch', 'Qual é a habilidade especial do herói *Tracer* em *Overwatch*?', 'Recall, que permite voltar no tempo e recuperar saúde.')
criaCartao('Overwatch', 'Em *Overwatch*, qual é o papel do herói *Mercy*?', 'Suporte, curando e ressuscitando aliados.')
criaCartao('World of Warcraft', 'Em *World of Warcraft*, qual é o nome do continente onde a maior parte do jogo acontece?', 'Azeroth.')
criaCartao('World of Warcraft', 'Qual é a raça de jogadores conhecida por sua afinidade com a natureza em *World of Warcraft*?', 'Druidas.')
criaCartao('Cyberpunk 2077', 'Em *Cyberpunk 2077*, qual é o nome da cidade futurística onde o jogo se passa?', 'Night City.')
criaCartao('Cyberpunk 2077', 'Qual é o nome do protagonista de *Cyberpunk 2077*?', 'V.')
criaCartao('The Witcher 3', 'Quem é o protagonista de *The Witcher 3: Wild Hunt*?', 'Geralt de Rivia.')
criaCartao('The Witcher 3', 'Em *The Witcher 3*, qual é o nome do objetivo principal de Geralt?', 'Procurar sua filha adotiva, Ciri.')
criaCartao('Valorant', 'Em *Valorant*, qual é o objetivo principal no modo de jogo "Search and Destroy"?', 'Atacar ou defender um ponto de bomba.')
criaCartao('Valorant', 'Em *Valorant*, o que é um "Agent"?', 'Um personagem jogável com habilidades únicas.')
criaCartao('Fall Guys', 'Qual é o objetivo principal em *Fall Guys: Ultimate Knockout*?', 'Ser o último jogador a sobreviver ao longo das rodadas de mini-jogos.')
criaCartao('Fall Guys', 'Em *Fall Guys*, como os jogadores são eliminados?', 'Fazendo-os cair ou ser derrotados durante as provas.')
criaCartao('Red Dead Redemption 2', 'Qual é o nome da gangue que o protagonista Arthur Morgan faz parte em *Red Dead Redemption 2*?', 'Van der Linde Gang.')
criaCartao('Red Dead Redemption 2', 'Em *Red Dead Redemption 2*, qual é o principal tema do jogo?', 'A vida de fora da lei no fim da Era do Velho Oeste.')
criaCartao('Hollow Knight', 'Qual é o nome do protagonista de *Hollow Knight*?', 'O Cavaleiro (The Knight).')
criaCartao('Hollow Knight', 'Em *Hollow Knight*, qual é a principal mecânica do jogo?', 'Exploração de um mundo subterrâneo cheio de inimigos e mistérios.')
criaCartao('Among Us', 'Qual é o objetivo dos impostores em *Among Us*?', 'Sabotar a missão e eliminar os tripulantes sem ser pego.')
criaCartao('Among Us', 'Em *Among Us*, como os jogadores podem descobrir quem é o impostor?', 'Fazendo reuniões e discutindo as evidências coletadas.')
criaCartao('Resident Evil Village', 'Em *Resident Evil Village*, qual é o nome da vilã principal?', 'Lady Dimitrescu.')
criaCartao('Resident Evil Village', 'Qual é o nome do protagonista de *Resident Evil Village*?', 'Ethan Winters.')
criaCartao('Destiny 2', 'Em *Destiny 2*, o que é o papel de um "Guardião"?', 'Proteger a Última Cidade e combater as forças das trevas.')
criaCartao('Destiny 2', 'Qual é a principal atividade multiplayer em *Destiny 2*?', 'Raids e Strikes.')
criaCartao('Monster Hunter: World', 'Qual é o objetivo principal de *Monster Hunter: World*?', 'Caçar e derrotar gigantescos monstros.')
criaCartao('Monster Hunter: World', 'Em *Monster Hunter: World*, o que pode ser feito com as partes dos monstros derrotados?', 'Fazer armaduras e armas.')
criaCartao('Minecraft Dungeons', 'Qual é o estilo de jogo de *Minecraft Dungeons*?', 'Ação e RPG, com masmorras geradas aleatoriamente.')
criaCartao('Minecraft Dungeons', 'Em *Minecraft Dungeons*, qual é o objetivo do jogador?', 'Explorar masmorras, derrotar inimigos e coletar loot.')
criaCartao('Sea of Thieves', 'Em *Sea of Thieves*, qual é o objetivo principal do jogo?', 'Ser um pirata, caçar tesouros e competir com outros jogadores.')
criaCartao('Sea of Thieves', 'Em *Sea of Thieves*, como os jogadores navegam pelo oceano?', 'Usando um navio e completando missões.')
criaCartao('Rocket League', 'Em *Rocket League*, como o futebol é jogado?', 'Com carros controlados pelos jogadores, usando uma bola gigante.')
criaCartao('Rocket League', 'Qual é o modo mais comum de jogo em *Rocket League*?', 'Modo competitivo 3v3.')
criaCartao('Genshin Impact', 'Em *Genshin Impact*, o que são "Visões"?', 'Elementos mágicos que permitem aos personagens usar habilidades elementares.')
criaCartao('Genshin Impact', 'Qual é o objetivo do protagonista em *Genshin Impact*?', 'Procurar seu irmão perdido e desvendar os mistérios do mundo de Teyvat.')
criaCartao('The Elder Scrolls V: Skyrim', 'Em *Skyrim*, qual é o nome do protagonista?', 'O Dragonborn.')
criaCartao('The Elder Scrolls V: Skyrim', 'Qual é a principal habilidade do protagonista em *Skyrim*?', 'Ele é capaz de usar gritos poderosos conhecidos como Thu’um.')
criaCartao('Pokémon', 'Em *Pokémon*, qual é o objetivo principal do jogador?', 'Capturar Pokémon e se tornar o campeão da liga Pokémon.')
criaCartao('Pokémon', 'Em *Pokémon*, como se chama o mestre Pokémon do primeiro jogo?', 'Red.')
criaCartao('Dota 2', 'Qual é o nome do campo de batalha principal em *Dota 2*?', 'The Dota 2 Map (ou Diretide).')
criaCartao('Dota 2', 'Quantos jogadores formam uma equipe em *Dota 2*?', '5 jogadores por equipe.')
